package com.climb.api.model.enums;

public enum PipelineHistoricoTipo {
    CRIACAO_NEGOCIO,
    ALTERACAO_DADOS,
    ALTERACAO_RESPONSAVEL,
    MOVIMENTACAO_ETAPA,
    CRIACAO_TAREFA,
    ALTERACAO_TAREFA,
    CONCLUSAO_TAREFA,
    CANCELAMENTO_TAREFA,
    COMENTARIO_ADICIONADO,
    ALTERACAO_VALOR_PROPOSTA,
    FECHAMENTO,
    PERDA,
    REATIVACAO,
    CONVERSAO_CONTRATO,
    CADENCIA_INICIADA,
    CADENCIA_TAREFA_CRIADA,
    CADENCIA_CONCLUIDA
}
